### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Strugglemeat** [mclewell/licheepi-nano-lcd#1]
I can clone the repo and run submodule update in the repo directory, that creates the buildroot submodule
however, from there, the instructions don't work

> cd licheepi-nano-lcd/software/buildroot

I guess this means to go to licheepi-nano-lcd/buildroot since there is no software directory
entering buildroot directory, I then mkdir output-sd and cd into it, then run the command
> make -C ../ O=$(pwd) BR2_EXTERNAL=$PWD/../../ boysenboard_spi_defconfig

this is the result

> make: Entering directory '/home/myusername/licheenano/licheepi-nano-lcd/buildroot'
> make: *** No rule to make target 'boysenboard_spi_defconfig'.  Stop.
> make: Leaving directory '/home/myusername/licheenano/licheepi-nano-lcd/buildroot'

any tips? thank you

**Comment by mclewell** [comment]
Oops, that is a copy-paste error from another one of my projects.

The instructions should be:
- `git clone https://github.com/mclewell/licheepi-nano-lcd`
- `cd licheepi-nano-lcd/`
- `git submodule update --init`
- `cd buildroot/` <-- here's the first correction
- `mkdir output-sd`
- `cd output-sd/`
- ` make -C ../ O=$(pwd) BR2_EXTERNAL=$PWD/../../ licheepi_nano_lcd_sd_defconfig` <-- here's the second correction
- Optional: configure buildroot using `make menuconfig`
- `make`

What's happening is buildroot is trying to find a defconfig in the `configs` dir at the root of the repo.

**Comment by Strugglemeat** [comment]
awesome! it's making now, I've got my fingers crossed. I've tried sooo many of the buildroot repos for this board, both locally (manjaro) and using docker, and I've had no success. I actually just emailed someone from the buildroot team and asked them to add support for this board since they already have lichee pi zero. thanks again.
